### ISSUE TITLE
Get Groupe Member

### ISSUE THREAD

**Issue by KevinAnass** [calico-crusade/WolfLive.Api#1]
How I can Get All The users inside the group

**Comment by calico-crusade** [comment]
Please update to v1.2.2 once it is available on Nuget.
Once you have updated you can access all of the users on a particular group using the following code inside of a command:
```CSharp
var users = await this.Client.GetGroupUsers(Group.Id);
```

There is an example of this available [here](https://github.com/calico-crusade/WolfLive.Api/blob/515656b5917064ee6371c991d2b038648af01893/WolfLive.Api.Cli/Commands/TestCommands.cs#L132). If this does not work for you, please reopen the issue.

There was an issue with the existing API where it was using an old version of the packet logic. This has been remedied.

**Comment by KevinAnass** [comment]
thank you so much

**Comment by calico-crusade** [comment]
No problem!

**Comment by KevinAnass** [comment]
I am sorry but is throwing this exception 
Error while deserializing packet: 400
{
  "code": 400
}

**Comment by calico-crusade** [comment]
Code 400 normally means the packet was malformed, which indicates that the group ID that you're requesting isn't valid. 
Could you send me an example of the code you're using to call the GetGroupUsers function?

**Comment by KevinAnass** [comment]
var groupusers = (await client.GetGroupUsers(3687058));

**Comment by calico-crusade** [comment]
Is 3687058 a valid group? I am getting a 403 error when I attempt to request this group's users as I'm not in it.

**Comment by KevinAnass** [comment]
yes I got this group from the Groups function you can try any group you are in

**Comment by calico-crusade** [comment]
Ok, I believe I have figured out the issue. There are too many users in the request. The request for user profiles will probably need to be broken up into separate calls. I will work on implementing this.

**Comment by KevinAnass** [comment]
thank you so much 
I am waiting for you

**Comment by calico-crusade** [comment]
It should work now. Please update to v1.2.3 of the nuget package. 

A thing to note; if you're requesting a group with more than 100 users, that call will take a while. To avoid a service timeout, throttle and potential account bar, I had to put a 1 second time out after every 4 requests of 25 users. Please open this issue again, if it is still not working.

**Comment by KevinAnass** [comment]
thank you so much  it's working without exception

**Comment by calico-crusade** [comment]
Awesome! Feel free to open another issue if you run into anything else, or if you want to suggest features!

**Comment by KevinAnass** [comment]
thank you
