### ISSUE TITLE
Get Groupe Memeber

### ISSUE THREAD

**Issue by KevinAnass** [calico-crusade/WolfLive.Api#3]
when I want to get a list of users in a group the second time 
throw me this exception
Error while deserializing packet: 400
{
  "code": 400
}

**Comment by calico-crusade** [comment]
Please provide more information as to the issue. I cannot recreate your issue.

**Comment by KevinAnass** [comment]
I explain what happens to me :
first I log in to the first account and it extracts the users from group normal but when I log in to another account  without refresh anything (I am using asp .net core just replace email and password input with a new one ) and login throw me this exception and not get the users 
Is that helpful?

**Comment by calico-crusade** [comment]
I still cannot recreate this issue. I've tried switching between accounts but I have not received a 400 error any of the times. Could you share the code that is causing an issue?

**Comment by KevinAnass** [comment]
thank you I fix it by creating a new object every time thank you but the speed of extract is slow any solution about this?

**Comment by calico-crusade** [comment]
This is an issue with Wolf specifically. You can only request 25 users at a time, I had to add a 1 second delay after every 100 members to avoid a service interruption, throttle or potential account bar. I explained this in #1 if you want more information. There really isn't a _decent_ solution other than waiting for it to resolve the users list.

**Comment by KevinAnass** [comment]
thank you so much and i am sorry if I bothering you
